version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoceste_frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
